# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SkNYBzDfZCycG7ijybgMwb7TqFpIWql
"""

!pip install -q transformers datasets scikit-learn torch

import json

data = [
  {"text": "I can't seem to locate my account settings.", "label": "Navigation_Problem"},
  {"text": "Where did the logout button go?", "label": "Navigation_Problem"},
  {"text": "How do I get back to the main dashboard?", "label": "Navigation_Problem"},
  {"text": "The link to the privacy policy is missing.", "label": "Navigation_Problem"},
  {"text": "I'm struggling to find the billing history.", "label": "Navigation_Problem"},
  {"text": "Is there a way to access the archived messages?", "label": "Navigation_Problem"},
  {"text": "The sidebar navigation completely disappeared.", "label": "Navigation_Problem"},
  {"text": "I can't find the option to delete my account.", "label": "Navigation_Problem"},
  {"text": "Where do I click to edit my profile?", "label": "Navigation_Problem"},
  {"text": "The cart icon is not showing up anywhere.", "label": "Navigation_Problem"},
  {"text": "I'm lost trying to find the contact us page.", "label": "Navigation_Problem"},
  {"text": "How do I navigate to the previous screen?", "label": "Navigation_Problem"},
  {"text": "I don't see the submit button on this page.", "label": "Navigation_Problem"},
  {"text": "Where is the search function located?", "label": "Navigation_Problem"},
  {"text": "The dropdown menu doesn't expand when I click it.", "label": "Navigation_Problem"},
  {"text": "I can't track down the notification bell.", "label": "Navigation_Problem"},
  {"text": "Where can I view my saved items?", "label": "Navigation_Problem"},
  {"text": "The footer links are completely hidden.", "label": "Navigation_Problem"},
  {"text": "I'm unable to find the FAQ section.", "label": "Navigation_Problem"},
  {"text": "How do I reach the upgrade page?", "label": "Navigation_Problem"},

  {"text": "What does this red triangle icon signify?", "label": "UI_Confusion"},
  {"text": "This error code 'ERR_502' means nothing to me.", "label": "UI_Confusion"},
  {"text": "The phrasing on this subscription tier is vague.", "label": "UI_Confusion"},
  {"text": "I'm confused by the layout of this calendar.", "label": "UI_Confusion"},
  {"text": "Why are there two different 'save' buttons?", "label": "UI_Confusion"},
  {"text": "The instructions for this form are contradictory.", "label": "UI_Confusion"},
  {"text": "I don't understand what 'sync disabled' implies here.", "label": "UI_Confusion"},
  {"text": "This popup doesn't explain what went wrong.", "label": "UI_Confusion"},
  {"text": "The color scheme makes the text unreadable.", "label": "UI_Confusion"},
  {"text": "I'm not sure if my changes were actually saved.", "label": "UI_Confusion"},
  {"text": "What is the difference between 'archive' and 'delete'?", "label": "UI_Confusion"},
  {"text": "The terminology used in this dropdown is too technical.", "label": "UI_Confusion"},
  {"text": "This chart is visually overwhelming and hard to read.", "label": "UI_Confusion"},
  {"text": "I don't get why this field is marked as required.", "label": "UI_Confusion"},
  {"text": "The feedback message just says 'failed' with no context.", "label": "UI_Confusion"},
  {"text": "I am baffled by how this filter system works.", "label": "UI_Confusion"},
  {"text": "What does the toggle switch next to my name do?", "label": "UI_Confusion"},
  {"text": "The icons on the toolbar lack labels.", "label": "UI_Confusion"},
  {"text": "This whole settings page is a mess.", "label": "UI_Confusion"},
  {"text": "I have no idea what action this prompt wants me to take.", "label": "UI_Confusion"},

  {"text": "I need to cancel my active subscription.", "label": "User_Goal"},
  {"text": "How do I upload a new profile picture?", "label": "User_Goal"},
  {"text": "I am trying to export this data to a CSV.", "label": "User_Goal"},
  {"text": "My objective is to merge these two accounts.", "label": "User_Goal"},
  {"text": "I want to upgrade to the premium plan.", "label": "User_Goal"},
  {"text": "I need to request a refund for my last purchase.", "label": "User_Goal"},
  {"text": "Trying to share this document with my team.", "label": "User_Goal"},
  {"text": "I want to permanently delete my data.", "label": "User_Goal"},
  {"text": "I am looking to integrate this with my existing tools.", "label": "User_Goal"},
  {"text": "I need to recover my lost username.", "label": "User_Goal"},
  {"text": "I want to set up two-factor authentication.", "label": "User_Goal"},
  {"text": "Trying to schedule a meeting for next week.", "label": "User_Goal"},
  {"text": "I need to update my credit card on file.", "label": "User_Goal"},
  {"text": "I want to view my performance analytics.", "label": "User_Goal"},
  {"text": "I am attempting to connect my bank account.", "label": "User_Goal"},
  {"text": "How do I invite a new user to my workspace?", "label": "User_Goal"},
  {"text": "I want to check the status of my support ticket.", "label": "User_Goal"},
  {"text": "Trying to find a way to bulk delete emails.", "label": "User_Goal"},
  {"text": "I need to generate a monthly invoice.", "label": "User_Goal"},
  {"text": "I want to customize my email preferences.", "label": "User_Goal"},

  {"text": "Can we get a native desktop app?", "label": "Feature_Request"},
  {"text": "It would be awesome to have a Slack integration.", "label": "Feature_Request"},
  {"text": "Please add support for biometric login.", "label": "Feature_Request"},
  {"text": "I really wish there was a keyboard shortcut for this.", "label": "Feature_Request"},
  {"text": "You should implement a dark theme for the dashboard.", "label": "Feature_Request"},
  {"text": "Would love to see an auto-save feature.", "label": "Feature_Request"},
  {"text": "Can you add a way to filter by date range?", "label": "Feature_Request"},
  {"text": "It needs a drag-and-drop interface for file uploads.", "label": "Feature_Request"},
  {"text": "Please introduce a loyalty rewards program.", "label": "Feature_Request"},
  {"text": "I'd like an option to customize the dashboard widgets.", "label": "Feature_Request"},
  {"text": "Adding a live chat support option would be incredibly helpful.", "label": "Feature_Request"},
  {"text": "It would be great if I could export directly to PDF.", "label": "Feature_Request"},
  {"text": "Please add multi-language support.", "label": "Feature_Request"},
  {"text": "I wish there was a way to duplicate existing projects.", "label": "Feature_Request"},
  {"text": "You need to add a 'select all' checkbox.", "label": "Feature_Request"},
  {"text": "Would be nice to have SMS notifications.", "label": "Feature_Request"},
  {"text": "Can we get more detailed analytics reports?", "label": "Feature_Request"},
  {"text": "Please allow users to set custom avatars.", "label": "Feature_Request"},
  {"text": "I'd love an offline mode for when I don't have internet.", "label": "Feature_Request"},
  {"text": "It should have a built-in spelling checker.", "label": "Feature_Request"},

  {"text": "The app crashes every time I try to upload a video.", "label": "Workflow_Issue"},
  {"text": "It takes way too many clicks to just send a simple message.", "label": "Workflow_Issue"},
  {"text": "The registration process is overly complicated.", "label": "Workflow_Issue"},
  {"text": "I keep getting looped back to the login screen.", "label": "Workflow_Issue"},
  {"text": "The data export is taking over an hour.", "label": "Workflow_Issue"},
  {"text": "Why do I have to re-enter my address every single time?", "label": "Workflow_Issue"},
  {"text": "The verification email takes too long to arrive.", "label": "Workflow_Issue"},
  {"text": "The whole onboarding flow feels very disjointed.", "label": "Workflow_Issue"},
  {"text": "It freezes whenever I switch between tabs.", "label": "Workflow_Issue"},
  {"text": "I lost all my progress because the session timed out too fast.", "label": "Workflow_Issue"},
  {"text": "The checkout flow is clunky and slow.", "label": "Workflow_Issue"},
  {"text": "Having to approve every single request manually is a bottleneck.", "label": "Workflow_Issue"},
  {"text": "The search function is painfully sluggish.", "label": "Workflow_Issue"},
  {"text": "I'm stuck in an endless captcha loop.", "label": "Workflow_Issue"},
  {"text": "The app drains my battery really quickly during video calls.", "label": "Workflow_Issue"},
  {"text": "Updating the software forces a complete system restart.", "label": "Workflow_Issue"},
  {"text": "The transition between pages is very laggy.", "label": "Workflow_Issue"},
  {"text": "I keep getting logged out randomly while working.", "label": "Workflow_Issue"},
  {"text": "The password reset link expires before I can even open it.", "label": "Workflow_Issue"},
  {"text": "Syncing data between my devices is completely unreliable.", "label": "Workflow_Issue"}
]

with open("data.json", "w") as f:
    json.dump(data, f)

print("Dataset created")

import json
import torch
from sklearn.preprocessing import LabelEncoder
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
from sklearn.metrics import accuracy_score, precision_recall_fscore_support


with open("data.json", "r") as f:
    raw_data = json.load(f)

texts = [item["text"] for item in raw_data]
labels = [item["label"] for item in raw_data]


label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)


dataset = Dataset.from_dict({
    "text": texts,
    "label": encoded_labels
})


model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(example):
    return tokenizer(
        example["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

dataset = dataset.map(tokenize_function, batched=True)
dataset = dataset.train_test_split(test_size=0.2)

# Load model
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(label_encoder.classes_)
)

# Metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = torch.argmax(torch.tensor(logits), dim=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average="weighted"
    )
    acc = accuracy_score(labels, predictions)
    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }


training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=40,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    load_best_model_at_end=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    compute_metrics=compute_metrics
)

# Train
trainer.train()

# Save model
model.save_pretrained("./intent_model")
tokenizer.save_pretrained("./intent_model")

print("Training complete!")

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import numpy as np

# Load model
model = AutoModelForSequenceClassification.from_pretrained("./intent_model")
tokenizer = AutoTokenizer.from_pretrained("./intent_model")

model.eval()

# Test sentence
text = "we nedd a button"

inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

with torch.no_grad():
    outputs = model(**inputs)

logits = outputs.logits
predicted_class_id = torch.argmax(logits, dim=1).item()

predicted_label = label_encoder.inverse_transform([predicted_class_id])[0]

print("Input:", text)
print("Predicted Intent:", predicted_label)

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import numpy as np

# Load model
model = AutoModelForSequenceClassification.from_pretrained("./intent_model")
tokenizer = AutoTokenizer.from_pretrained("./intent_model")

texts=["we need a button","i dont know how to create an account","its confusing"];



for i in texts:
  inputs = tokenizer(i, return_tensors="pt", truncation=True, padding=True)
  with torch.no_grad():
    outputs = model(**inputs)
  logits = outputs.logits
  predicted_class_id = torch.argmax(logits, dim=1).item()
  predicted_label = label_encoder.inverse_transform([predicted_class_id])[0]
  print("Input:", i)
  print("Predicted Intent:", predicted_label)

import json

data = [
    {"text": "I couldn't find the login button", "label": "Navigation_Problem"},
    {"text": "The checkout page is confusing", "label": "UI_Confusion"},
    {"text": "I want to change my password", "label": "User_Goal"},
    {"text": "It would be nice to have dark mode", "label": "Feature_Request"},
    {"text": "The submit button is hard to locate", "label": "Navigation_Problem"},
    {"text": "I don’t understand this error message", "label": "UI_Confusion"},
    {"text": "I was trying to update my profile", "label": "User_Goal"},
    {"text": "The form takes too long to complete", "label": "Workflow_Issue"},
    {"text": "I can't find the checkout option", "label": "Navigation_Problem"},
    {"text": "This layout is very confusing", "label": "UI_Confusion"}
]

with open("data.json", "w") as f:
    json.dump(data, f)

print("Dataset created")